### ISSUE TITLE
Bug - 1.18-9.0.3 Crashes the game with Mixin to class_310

### ISSUE THREAD

**Issue by 3e2j** [jaredlll08/Controlling#102]
Full Crash log - Seems to be a Mixin error
[latest.log](https://github.com/jaredlll08/Controlling/files/7653185/latest.log)

**Comment by Aridastle** [comment]
I am having the same Mixin error.
[latest.log](https://github.com/jaredlll08/Controlling/files/7653690/latest.log)

**Comment by JustFoxx** [comment]
I am having the same error
[latest.log](https://github.com/jaredlll08/Controlling/files/7653798/latest.log)

**Comment by XxFallenAngelxX** [comment]
[14:36:45] [main/WARN]: Reference map 'controlling.refmap.json' for controlling.mixins.json could not be read.

**Comment by jaredlll08** [comment]
Sorry for taking so long on this, ended up making a few other changes while I was at it.
