### ISSUE TITLE
crash after searching "exp" in controlling menu

### ISSUE THREAD

**Issue by freopt** [jaredlll08/Controlling#114]
[crash-2022-02-10_16.03.11-client.txt](https://github.com/jaredlll08/Controlling/files/8044264/crash-2022-02-10_16.03.11-client.txt)

**Comment by freopt** [comment]
[options.txt](https://github.com/jaredlll08/Controlling/files/8044315/options.txt)

**Comment by freopt** [comment]
might be oreexcavation

I replaced it with ultimine and everythings fine now

**Comment by jaredlll08** [comment]
Report it to ore excavation then, there is nothing I can do on my side.
