### ISSUE TITLE
\n in fabric.mixin.json breaks standard json compat

### ISSUE THREAD

**Issue by MrNavaStar** [jaredlll08/Controlling#115]
Working on a mod manger that reads mods fabric.mixin.json files and the \n in the description breaks it. I have a work around but thought I would ask for a fix anyway.

**Comment by jaredlll08** [comment]
I didn't even know it was there, fixed :) https://github.com/jaredlll08/Controlling/commit/0b5037b953e707bb10d284b280293029e17cf758
