### ISSUE TITLE
Incompatibility with optifine 

### ISSUE THREAD

**Issue by xelotex** [jaredlll08/Controlling#117]
When i combine this mod with optifine, it is imposible to do key combinations, for example: "shift + H"
I'm playing with the version 1.18.1-9.0+15 of controlling, and with the version 1.18.1_HD_U_H4 of optifine.

**Comment by jaredlll08** [comment]
what modloader?

**Comment by xelotex** [comment]
> what modloader?

Forge

**Comment by jaredlll08** [comment]
Just to confirm, the issue isn't present with just optifine and forge?

**Comment by xelotex** [comment]
> Just to confirm, the issue isn't present with just optifine and forge?

it isn't

**Comment by jaredlll08** [comment]
Optifine is a black box, I have tried to debug code with it before and it never ends well, unfortunately this issue will not be fixed (I'm also still not sure why optifine would do anything with key bindings)
