### ISSUE TITLE
[1.12] Suggestion - Re Position UI Elements

### ISSUE THREAD

**Issue by SnowShock35** [jaredlll08/Controlling#12]
Hi @jaredlll08 

In the latest version of Controlling you added an additional button to the controls menu UI. While I like the buttons function (Glad it finally got added), but there appears to be some issues with sizing and positioning, observe the following:

![](https://ss.blamesnow.co.uk/2017/06/1498734827-2a99be49.png)

1. The button on the left has literally zero padding around the text on the left and right meaning it's squashed up to the sides and therefore could use being a tad wider
2. The top two buttons don't match the length of the bottom button
3. As you can see on the left the done button doesn't match the size of the search box.

**Comment by jaredlll08** [comment]
The searchbar is because of padding added in the texture, in code it is the same size.

The buttons on the right, I got no idea on a fix, I don't have much space to work with
