### ISSUE TITLE
Suggestion: Mixed Input Compatibility

### ISSUE THREAD

**Issue by AmbrosiaEgg** [jaredlll08/Controlling#125]
For users who would set up the game using a level of Mixed Input (e.g. Steam Deck Users using Mouse and Controller Inputs interchangably) It would be helpful to have a setting in the config allowing the controller UI to stay on screen during Mouse Input.

**Comment by jaredlll08** [comment]
What controller ui?

Make sure you have the right mod, there is a mod called "controllable" which adds controller support, this mod just changes the key binding menu

**Comment by jaredlll08** [comment]
Closing due to no reply, and most likely not even related to this mod.
