### ISSUE TITLE
No 1.16.5 on curseforge

### ISSUE THREAD

**Issue by TheGrandJaggard** [jaredlll08/Controlling#126]
I cannot find any 1.16.5 version of this mod on curseforge and I can't seem to find it anywhere else.

**Comment by jaredlll08** [comment]
https://www.curseforge.com/minecraft/mc-mods/controlling/files/all?filter-status=1&filter-game-version=1738749986%3A70886

**Comment by TheGrandJaggard** [comment]
I see I was missing the "show all" button. Thanks!
