### ISSUE TITLE
CurseForge mark on Controlling compitable with 1.19.2

### ISSUE THREAD

**Issue by Disguys** [jaredlll08/Controlling#127]
Hello, please put a note on CurseForge that it is compatible with 1.19.2, I need it for the Modpack.

**Comment by wolvyreen** [comment]
I second this.

**Comment by jaredlll08** [comment]
Closed by https://github.com/jaredlll08/Controlling/commit/a2b493fee9c04b742c98dbea128ed3701631f5e3
