### ISSUE TITLE
Suggestion: Compatibility with the Rebind mod (1.7.10-1.12.2)

### ISSUE THREAD

**Issue by HRudyPlayZ** [jaredlll08/Controlling#128]
Rebind is a neat mod that lets players hide keybinds, change their name and category, reorganizing the menu overall.
It also allows to merge keybinds together or outright disable them.
As Controlling overwrites the GUI, the mod cannot work properly and as such can't do much. A fix would be to have Controlling replicate the mod's logic if its installed.

Here is the curseforge page of Rebind: https://www.curseforge.com/minecraft/mc-mods/rebind

**Comment by jaredlll08** [comment]
I'm not going to be reimplementing another mod myself, unfortunately this may just be one of those things that doesn't work.

Also really doesn't help that this is for ancient versions.
