### ISSUE TITLE
Suggestion: Export key binds to share with others

### ISSUE THREAD

**Issue by freecoffees** [jaredlll08/Controlling#129]
I'm not quite sure how to share my key binds, and I need to since the mods I use for a server default to conflicting keys.
I resorted to exporting my entire instance with other players but it's a hassle whenever I add one small mod. Would be nice if there's a config file or something?

**Comment by jaredlll08** [comment]
I don't change anything about how keybindings are stored, they are all stored in the vanilla `options.txt` file, so you could copy that to new instances?

**Comment by freecoffees** [comment]
Ah, thank you! I didn't know you could do that.
