### ISSUE TITLE
Bug: Cannot deselect search box

### ISSUE THREAD

**Issue by Shoes4Clues** [jaredlll08/Controlling#139]
This has multiple side effects, including typing when rebinding a key and being unable to unbind a key.
Version is Controlling-fabric-1.18.2-9.0+22.jar

**Comment by jaredlll08** [comment]
I'm unable to reproduce, simply clicking off the search box deselects it.

**Comment by Tooey345** [comment]
I'm using Controlling-forge-1.18.2-9.0+22 and have been able to get it happen with debugify installed.  Attempting to change a key bind but clearing the keybind with ESC key can then cause the search box to capture input focus of the keyboard and wont release it.  happened with the latest 3 versions of Debugify installed. removed the mod and its stopped happening.

**Comment by jaredlll08** [comment]
Report that to them, after testing it myself, they seem to be doing weird things with edit box focus, it seems as if a screen has at-least one EditBox, then at-least one of them needs to be focused at all times? No idea what they are trying to solve, if anything I feel as though they have introduced a bug.
