### ISSUE TITLE
Crashes when opening control menu

### ISSUE THREAD

**Issue by cheetahcat19** [jaredlll08/Controlling#142]
https://bytebin.lucko.me/rBbKN7D4Wp

**Comment by jaredlll08** [comment]
If you remove Controlling, does it still crash?

**Comment by cheetahcat19** [comment]
> If you remove Controlling, does it still crash?

it is still crashing after being removed.

**Comment by jaredlll08** [comment]
Then this isn't an issue with Controlling.

One of your mods has an invalid keybinding, unfortunately there isn't any information in the log pointing to which one, I would recommend removing mods until it stops crashing to figure out which one it is
