### ISSUE TITLE
Can't bind anything to Enter key

### ISSUE THREAD

**Issue by Phaxtolgia** [jaredlll08/Controlling#143]
First thing I do when I boot a new instance of Minecraft, I bind chat to Enter, but this mod causes a conflict with itself and does not allow me to bind Enter to chat.

**Comment by jaredlll08** [comment]
fixed by https://github.com/jaredlll08/Controlling/commit/ad064f5b48b6c01ae1772cf0fbf0fec7ef4b6b93
