### ISSUE TITLE
Lack of support for GUI scale large

### ISSUE THREAD

**Issue by SnowShock35** [jaredlll08/Controlling#15]
Hi,

I believe to have found an issue with Controlling. The issue regards GUI scaling - your favourite, right? On the large setting for GUI scale the text is cut off half the screen making it unreadable. This issue has become very common given the amount of people that use this specific setting. 

#### Issue details

- Minecraft 1.12.2
- Minecraft Forge 14.23.0.2529
- Controlling 3.0.3 (taken from FML's mods menu)

#### Issue description

When using the GUI scale setting of `Large` or `Auto` (auto isn't consistent as it's dependant on screen resolution / aspect ratio) The text that is displayed to the left of the control's name (in parenthesis) is cut off the screen and cannot be fully seen.

#### Issue solution

To not display it when the GUI scale is set to `Large` or find another way of displaying it within the GUI. 

#### Issue media

Normal GUI Scale:
![Issue media #1](https://ss.blamesnow.co.uk/2017/11/1509897221-17412792.png) 

Large GUI Scale:
![Issue media #2](https://ss.blamesnow.co.uk/2017/11/1509897269-9f4f69f6.png)

**Comment by jaredlll08** [comment]
Update controlling.

**Comment by SnowShock35** [comment]
There's no newer update available?
