### ISSUE TITLE
suggestion: group conflicting keybinds based on key

### ISSUE THREAD

**Issue by art0007i** [jaredlll08/Controlling#152]
I think it would be better to group keybinds based on the key when in show conflicts mode, to make resolving conflicts easier.
![image](https://github.com/jaredlll08/Controlling/assets/19620451/7d69f0ec-5ac2-43eb-a34a-f62120800b61)
so in this image I would expect the order to be
- Strafe Left [a]
- Hotbar Slot 9 [a]
- Social Interaction Screen [a]
- Toggle Cinematic Camera [a]
- Strafe Right [b]
- Attack/Destroy [b]
- Hotbar Slot 1 [b]
- Swap Item in Offhand [b]

I took the screenshot while using Controlling version forge-1.18.2-9.0+23

**Comment by jaredlll08** [comment]
This has been implemented in 1.20.5 in the form of a new sort order, letting you sort by the key names instead of the key binding name

**Comment by art0007i** [comment]
@jaredlll08 can that be backported to 1.18.2? that's the version I originally made the report in and would still like it on that version.
