### ISSUE TITLE
Make Controlling compatible with Amecs

### ISSUE THREAD

**Issue by IntM4rco** [jaredlll08/Controlling#156]
You could make Controlling compatible with Amecs. 
It would be great to use them together however Amecs functions do not work with Controlling.
https://modrinth.com/mod/amecs

**Comment by jaredlll08** [comment]
Duplicate of https://github.com/jaredlll08/Controlling/issues/77

I would like them to be supported and have even gone out of my way to add events that other mods can use to ensure there is support, but I tried reaching out to Siphalor in the linked issue and have gotten no reply.

The only way this is going to get support is if Siphalor adds code to Amecs.
