### ISSUE TITLE
[1.20.1] Changing keybinds causes extra keys to be added

### ISSUE THREAD

**Issue by chorbintime** [jaredlll08/Controlling#157]
On the [BMC2 Fabric](https://legacy.curseforge.com/minecraft/modpacks/better-mc-fabric-bmc2/files/4654240) modpack, some players who attempt to rebind keybinds will have extra keys bound to that action, in addition to the key they pressed.

The most detailed report we got of the issue had the following information:
![image](https://github.com/jaredlll08/Controlling/assets/112908845/56115f5e-a6f7-41bc-a95e-b33666ed7f8c)
"before removing the mod, when i pressed button 5 fore sprint, it was c + button 5
Same for sneak, s + left sneak"

Removing the Controlling mod fixed the issue for this user. It seems that trying to reset the bind wouldn't do anything, as well. 
It's worth noting we use the YOSBR mod (Your Options Shall Be Respected), but I see no reason that would be causing this.

**Comment by jaredlll08** [comment]
The CarryOn mod pulls in AMECS which is not supported.

read https://github.com/jaredlll08/Controlling/issues/77 for more info

Controlling should have all the hooks amecs would need to have full support for modifier keys, and if it doesn't I'm more than happy to add any hooks that amecs needs to make the mods compatible.
