### ISSUE TITLE
Mod dependency for Controlling

### ISSUE THREAD

**Issue by PJRamaglia** [jaredlll08/Controlling#165]
Thoughts on adding and/or mentioning somewhere in the "Description" section of this mod how you also need the Searchables mod dependency as well?  I don't think the generic user would know enough to click on the Dependencies section on their own, you know?

![image](https://github.com/jaredlll08/Controlling/assets/3131378/00f58014-d190-4938-9f1d-dc15a0899f84)

**Comment by jaredlll08** [comment]
Personally I believe adding the dependencies to the description is not the solution to this, the description is for the whole project, regardless of version or modloader, where as each file can list its own dependencies (for example, fabric files require fabric-api)

> I don't think the generic user would know enough to click on the Dependencies section on their own, you know?

The generic user in your scenario will either be using a mod launcher like the CurseForge launcher, which handles mod dependencies, or they will learn *very* quickly that they need to look at the dependencies for each file.
