### ISSUE TITLE
"Reset Keys" button is always in the "Confirm?" state when entering the keybinds screen with any non-default key binds

### ISSUE THREAD

**Issue by VeilStar** [jaredlll08/Controlling#166]
Title. Using `Controlling-fabric-1.20.2-13.0.1.jar`, `Searchables-fabric-1.20.2-1.0.3.jar`, and `fabric-api-0.90.0+1.20.2.jar`. No other mods present.

**Comment by jaredlll08** [comment]
This was fixed by https://github.com/jaredlll08/Controlling/commit/7e8c76b288518da4a6e4a759d08b7c0134aed202
