### ISSUE TITLE
Can't set key combinations ~ Fabric

### ISSUE THREAD

**Issue by Hexblood** [jaredlll08/Controlling#169]
I have been running into this issue in several modern versions on Fabric. 1.19.2, 1.20.1, 1.20.2 being the versions I have mostly been working with.

I do not know if it is directly Controlling or if there is a conflict somewhere. So it there is any known incompatibilities on Fabric please let me know. Or if something has changed and I need to do something to add the second key now.

When I try to set a combination (i.e. "Shift + G") it sets the first key to register and sets it to that. So as soon as I press shift that gets locked in and the "input" phase closes, not taking the second key.

**Comment by jaredlll08** [comment]
Modifier key bindings is a feature added by Forge and other mods, fabric does not have it built in.

Do you have a mod installed that adds them?

**Comment by Hexblood** [comment]
Not that I am aware of. This is my first time messing with Fabric. I do not know what mods could add that function >,<;

**Comment by Hexblood** [comment]
It looks like a mod called Amecs might add that function. I'll test if they work together in a min.

**Comment by Hexblood** [comment]
Negative Ghost Rider. Amecs does add the capabilities to do modifiers, but it does not work with Controlling as the interface.

**Comment by jaredlll08** [comment]
Yea, that would be this issue https://github.com/jaredlll08/Controlling/issues/77

Unfortunately I don't know if a solution for modifier keys on fabric, and there is nothing wrong with Controlling itself, so I'm going to be closing this issue.
