### ISSUE TITLE
Use fabric-api instead of fabric mod ID for Fabric API

### ISSUE THREAD

**Issue by Poopooracoocoo** [jaredlll08/Controlling#190]
Users may be confused when they see that it depends on `fabric`, not knowing that it's referring to Fabric API.

>As of Minecraft 1.19.2, Fabric API's mod ID has changed from `fabric` to `fabric-api`. When backporting from 1.19.2 to earlier versions, you must alter the `depends` section of your `fabric.mod.json` to expect `fabric`.

From https://fabricmc.net/wiki/tutorial:setup#mod_setup

Line to change:
https://github.com/jaredlll08/Controlling/blob/1.20.1/fabric/src/main/resources/fabric.mod.json#L24

One example of a confused user:
https://www.reddit.com/r/fabricmc/comments/1bh5uws/inconpatible_mods_found_error_please_help/

**Comment by jaredlll08** [comment]
This should be solved in all relevant versions.

**Comment by Poopooracoocoo** [comment]
Btw FAPI for 1.18.2 and 1.19.2 actually uses the `fabric-api` mod ID now :)

**Comment by jaredlll08** [comment]
I'm not sure how comfortable I am with changing it on those versions, the wiki you linked said 1.19.3+, and I don't know if people are using the mod with an older fabric api from before they made the move.

**Comment by Poopooracoocoo** [comment]
Going rather off topic as I'm not at all affected by your decision.

I know some people use fabric-api-0.76.1+1.19.2 and fabric-api-0.76.0+1.18.2 for compatibility with mods that aren't compatible with Fabric API 0.77.0's core shader changes. FAPI 0.76.0 and above have the new mod ID.
