### ISSUE TITLE
Strange click behavior when reseting keybinds [1.21] [18.0.1]

### ISSUE THREAD

**Issue by TheRedstoneShark** [jaredlll08/Controlling#195]
Currently, it's very difficult and inconsistent to click the "Reset" button in the Key Binds menu.
Mod versions can be seen in the start of the demonstration videos.

https://github.com/user-attachments/assets/10b51abf-84df-4b9d-b8d8-3c21a4970081 

https://github.com/user-attachments/assets/c27128b1-87ed-424c-be5e-530d400f17cf

Logs: https://mclo.gs/9XfmbbQ

OS: Microsoft Windows 10 Home Version 10.0.19045 Build 19045
Processor: AMD Ryzen 7 5800HS with Radeon Graphics, 3201 Mhz, 8 Core(s), 16 Logical Processor(s)
GPU: NVIDIA GeForce GTX 1650

**Comment by opticGT** [comment]
im getting the same issue, its unplayable

**Comment by jaredlll08** [comment]
Fixed by https://github.com/jaredlll08/Controlling/commit/a88771e50d604effd524b44290f1cc3b4fe54876
