### ISSUE TITLE
keybinds switching to "left click" when left clicking done..

### ISSUE THREAD

**Issue by opticGT** [jaredlll08/Controlling#196]
i was trying to change my keybind for sprint from "ctrl" to "shift". but when i click off it thinks im trying to set my "left click" as my sprint, or any keybind i try to change, i thinks im trying to set my keybind to "left click" when i hit the "Done" button....
what i do..  
mod version: 18.0.1

**Comment by jaredlll08** [comment]
This is an issue with neoforge.
https://github.com/neoforged/NeoForge/issues/1278
which has a fix that they need to merge here
https://github.com/neoforged/NeoForge/pull/1350
