### ISSUE TITLE
"Show Conflicts" mode also shows unset keys

### ISSUE THREAD

**Issue by WesCook** [jaredlll08/Controlling#2]
Enabling "Show Conflicts" mode shows all keys that are unbound with "None".  This is probably not ideal.

![conflicts](https://cloud.githubusercontent.com/assets/792101/21746328/b234979c-d4f5-11e6-8f31-54c09ffc17de.png)

**Comment by jaredlll08** [comment]
Thing is, NONE is technically a conflicting key, and some people may want to show NONE.
