### ISSUE TITLE
[Feature Request] Specific-Case Hotkey Stacking

### ISSUE THREAD

**Issue by ElvenChaos** [jaredlll08/Controlling#24]
**Problem:** There are too many mods that add their own hotkey for two certain basic functionalities: Toggling and Cycling, and with each toggle/cycle wanting its own key bind, they key map gets cluttered fairly quickly, on top of remembering what cycles what gets confusing.

**Obstacle:** Each hotkey tends to _want_ its own keybind. Yes, you can spread them out across modifiers, but that still leads to clutter and unintuitive placement of keybinds. You can not simply stack hotkeys that cycle items from different mods onto the same keybind.

**Solution:** _Make your own hotkeys that press other hotkeys!_ Register your own configurable hotkeys that don't do much on their own other than activate other hotkeys. Let the player create the following hotkeys by defining what other hotkeys should be activated when pressed:

 •_Hotkey Type 1 -- Item Cycle (includes toggle)_: This hotkey will look at the item in the player's main hand (optional off hand instead) and grab the mod that the item comes from, matches the mod to the pre-selected hotkey from that mod, then tell the client/server that _that_ hotkey was pressed. This hotkey type only supports 1 hotkey per mod, though in the instance a mod implements a cycle forward and a cycle back, you could allow a second Hotkey type 1 to exist with a separate list, just bound to a different configurable key.

•_Hotkey Type 2 -- Use It All!_: This hotkey is a much simpler approach, in that it will attempt to use any and all hotkeys in its hotkey list in succession. This is good for when there isn't an item to hold in your hand, but you want to condense similar functionality to one key. For example, multiple mods could implement a Magnet hotkey that doesn't involve holding a magnet, or multiple mods may include a hotkey to affect each of their new armor sets, and players could condense each of those functionalities into their own keybinds.

If you would like some example mods that have item cycling keybinds:
1. [Exchangers](https://minecraft.curseforge.com/projects/exchangers)
2. [/dank/null](https://minecraft.curseforge.com/projects/dank-null)
3. [Mekanism](https://minecraft.curseforge.com/projects/mekanism) _Not sure if this one functions properly_
4. [Better Builder's Wands](https://minecraft.curseforge.com/projects/better-builders-wands)
5. [PlusTiC](https://minecraft.curseforge.com/projects/plustic/)
6. [CoFH Mods](https://minecraft.curseforge.com/projects/cofhcore) _Not sure under which mod exactly the keybinds are registered, as they are labeled under "CoFH Keys."_

**Summary:** Please create client-side hotkeys that, depending on what the player is holding and what the player has assigned to the "list" for that hotkey, "presses" the hotkey of another mod. If possible, this should function while leaving the hotkey from the "other mod" unbound.

**Comment by jaredlll08** [comment]
our of scope for this project.
