### ISSUE TITLE
[Feature Request] Pressing Esc while Controlling search box is in focus to exit menu

### ISSUE THREAD

**Issue by ryankhart** [jaredlll08/Controlling#28]
I would like it so that if I'm searching for something in Controlling that I can hit the Esc key on my keyboard as a shortcut for clicking on "Done" or unfocusing that search box. I don't care which one. I just don't like using the mouse when I don't have to.

**Comment by jaredlll08** [comment]
Would pressing esc to unfocus the text box work? that way you would have to press it twice to back out of the menu.

**Comment by ryankhart** [comment]
Yes, the more I think about it. Pressing Esc to unfocus the text box would be the preferable way since I get in the habit of pressing Esc after searching in JEI to unfocus that search field.
