### ISSUE TITLE
Not working in Forge 1.13.2

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [jaredlll08/Controlling#29]
![image](https://user-images.githubusercontent.com/25037295/55672264-bdf3fd00-58cb-11e9-881c-6a0abbccc4df.png)

**Comment by jaredlll08** [comment]
Can't do anything without logs or more info. I do have to say, 1.13 is not supported, not even by Forge at this point. CPW said to just leave 1.13 and go to 1.14.

**Comment by Pythonic-Rainbow** [comment]
There is no log mentioning about the mod.  
Anyways can u forward me what CPW said about the "Skip 1.13" thingy?

**Comment by jaredlll08** [comment]
It was said in stream, and it was in the context of

"1.14 exists and is way more developed than 1.13, you should update and use it"

**Comment by Pythonic-Rainbow** [comment]
thanks and oof
