### ISSUE TITLE
Controlling forge 1.14.2 crash log

### ISSUE THREAD

**Issue by Kylebartaous** [jaredlll08/Controlling#34]
Minecraft version: 1.14.2

Forge version: 26.0.63

Controlling mod version: 5.02

Crash report: https://pastebin.com/K3u25Rzx

latest-log: https://pastebin.com/bVv3G7na

* Well attempting to click on a key bind to clear it, this would cause a client crash. What i was trying is, click on the key bind, to then click on esc to clear it, to set it to another key.

* Then trying to use the in game gui scroll bar w/ in the control keybinds options, well having this mod, it would cause a client to crash.

**Comment by jaredlll08** [comment]
Fixed in latest version.
