### ISSUE TITLE
[1.7.10] Conflict with iChun mods?

### ISSUE THREAD

**Issue by xJon** [jaredlll08/Controlling#36]
As you can see [here](https://github.com/xJon/The-1.7.10-Pack/issues/1774#issuecomment-504739049), when trying to press `O` to reach the iChun mods settings, the controls menu pops and `O` is typed in. 
![2019-06-23_11-28-15](https://user-images.githubusercontent.com/8522686/59974941-09a07380-95aa-11e9-8dd5-728a01d46298.gif)
Doesn't happen with other letters as far as I could tell.
Any idea why this happens?
Thanks!

**Comment by jaredlll08** [comment]
Firstly 1.7.10 isn't supported.
Secondly I have no idea what is going on in your gif with those custom animation, no idea where it starts or ends. 

Ichuns way of accessing his keybind is incredibly stupid.

**Comment by xJon** [comment]
Custom animation is by the VoxelMenu mod. And as I said, it starts by trying to press O to reach the iChun mods settings, and ends by the controls menu popping up and O being typed in.
Thank you anyway!
