### ISSUE TITLE
Port to 1.14.4

### ISSUE THREAD

**Issue by TheMysticalBard** [jaredlll08/Controlling#39]
I would appreciate it if you could port to 1.14.4 (if it works, adding the version on CurseForge works as well) in order for modpack creators to update to more stable Forge versions. Thank you!

**Comment by jaredlll08** [comment]
I'm a bit confused, does the current version on curseforge work fine? Just that it isn't marked as 1.14.4?

**Comment by TheMysticalBard** [comment]
I'm not sure since I can't install it to a 1.14.4 profile on Twitch App.

**Comment by TheMysticalBard** [comment]
Installed Forge on regular client, seems to work just fine. Just needs the 1.14.4 tag on CurseForge. Thanks again.

**Comment by jaredlll08** [comment]
Done :)
