### ISSUE TITLE
A license, a license, my kingdom for a license! :)

### ISSUE THREAD

**Issue by magnusjjj** [jaredlll08/Controlling#4]
Can you license your code under an open source license of any kind? Mod looks awesome.

**Comment by jaredlll08** [comment]
I want your kingdom now.

**Comment by magnusjjj** [comment]
<3

You can have it. Its called Sweden, and It's.. well, its not the best. Right wing people in the parlaiment, and I guess you would have to evict the previous tenants but.. You know. The country is its people. Ahem.

I may just have done a 'selling the brooklyn bridge', https://en.wikipedia.org/wiki/Brooklyn_Bridge#In_popular_culture ;). *scuttles away*
