### ISSUE TITLE
[suggestion] Allow way to see what category (and/or mod) a control entry is from in search

### ISSUE THREAD

**Issue by fuzzyweapon** [jaredlll08/Controlling#44]
I'm not sure if tooltips are available to you?  But it'd be nice if when mousing over an entry, we could see the Category which a control belongs to.  Though as I think about it, it might be nice to include the mod name too, because it's really hard to figure out what mods various controls belong to (or write them up for those mods so they will put it in a better place, name it better, etc).

**Comment by fuzzyweapon** [comment]
FYI, I looked through the closed issues and it looks as if in the past, you've added some category or tooltips.  For reference, I'm not sure if these might be broken?  I'm on macOS - mojave, forge 28.1.61, Controlling 5.0.4.

**Comment by jaredlll08** [comment]
I forgot to port the feature over for 1.14, I'll do it when I have free time :)

**Comment by fuzzyweapon** [comment]
Cool, thank you!

**Comment by jaredlll08** [comment]
implemented in 1.14 and 1.15
