### ISSUE TITLE
Unbound keys show as conflicting

### ISSUE THREAD

**Issue by Naxanria** [jaredlll08/Controlling#45]
![image](https://user-images.githubusercontent.com/3246224/69535382-11f74300-0f7c-11ea-85dd-badabe946fc4.png)

You seem to have addressed this before https://github.com/jaredlll08/Controlling/issues/2 But now there is the `Show Unbound` button, This functionality might be nice to have now?

**Comment by jaredlll08** [comment]
implemented in 1.14 and 1.15
