### ISSUE TITLE
[1.15.2] Selection for Keybind does not work correct

### ISSUE THREAD

**Issue by realTIMematrix** [jaredlll08/Controlling#49]
The selection for keys seems to be not working correct.

I'm using:
Forge 31.0.1
Minecraft 1.15.2
Controlling 6.1.0

[Screenshot](https://gyazo.com/4783ea9b8c5964c1a9250c9072b96115)

Issue: I select the [X] for keys and enter only "a" (or other letters) but controlling shows me also other keybinds instead only the ones with "a". with digits it works fine but not with letters.

**Comment by jaredlll08** [comment]
That is because it is using the name of the "key", so if you select "key" and then type in "left", it will show all keybinds who's key name has the word "left" in it, like this:

![image](https://user-images.githubusercontent.com/5553605/73220640-99715600-4167-11ea-83e7-97ccf7397928.png)
