### ISSUE TITLE
Keys set to None (Show Conflicting Keys Button)

### ISSUE THREAD

**Issue by WenXin20** [jaredlll08/Controlling#5]
I noticed that when I disable a Keybinding (set it to None) so that I can figure out which ones I want to use a key for, they all display as conflicting, making hard to find the ones that are actually conflicting, especially when there are a lot of keybings. Can this be changed so that they don't display? Thanks

**Comment by jaredlll08** [comment]
See >https://github.com/jaredlll08/Controlling/issues/2

**Comment by jaredlll08** [comment]
If this isn't the same as #2, please show me a picture of what you mean.

**Comment by WenXin20** [comment]
Oh, Ok, it turns out it is, I just misread the title, so I didn't think to read what it was about. Thanks anyway
