### ISSUE TITLE
[1.15.2] When you click on the CheckBox and then on the Spacebar, it will activate / deactivate the CheckBox

### ISSUE THREAD

**Issue by TheDirectorX** [jaredlll08/Controlling#54]
![ScreenRecorderProject7](https://user-images.githubusercontent.com/43481085/79138269-b106c500-7dcd-11ea-98b7-41464fc902c2.gif)

**Versions:**
 - Forge Version: `31.1.35`
 - MC Version: `1.15.2`
 - Mod Version: `6.1.3` (on previous versions as well)

**Comment by jaredlll08** [comment]
This is an artifact of vanilla's "tab to focus" system, there isn't much I can do, it also happens on normal buttons, not only my check boxes.

The whole system is a mess, even vanilla's own guis suffer from issues with it

![image](https://user-images.githubusercontent.com/5553605/79174167-27212100-7dfa-11ea-9472-2636233e6802.png)


![image](https://user-images.githubusercontent.com/5553605/79174200-3e600e80-7dfa-11ea-9367-f015793fc454.png)
