### ISSUE TITLE
[Suggestion] When searching by Category, display the category at the top

### ISSUE THREAD

**Issue by TheDirectorX** [jaredlll08/Controlling#55]
![image](https://user-images.githubusercontent.com/43481085/79140542-99c9d680-7dd1-11ea-8128-694ce062307d.png)
![image](https://user-images.githubusercontent.com/43481085/79140612-afd79700-7dd1-11ea-8149-e31bb1167025.png)
### This will be visually more convenient when several categories have the same characters:
![image](https://user-images.githubusercontent.com/43481085/79140813-004ef480-7dd2-11ea-9a7b-ce2544717cc3.png)

**Comment by jaredlll08** [comment]
this only works with:
Sort: none
displaymode: all
