### ISSUE TITLE
[Suggestion] Display keybinds as ALLCAPS instead lowercase

### ISSUE THREAD

**Issue by 4rz0** [jaredlll08/Controlling#59]
Have the Keybinds shown in allcaps (like it has been ever since) instead of lowercase.
That would make certain keybinds more readable.
Not sure if this even needs an option to be disabled, but probably wouldn't hurt, just in case ;D

**Comment by jaredlll08** [comment]
I don't specify lowercase or uppercase. mojang changed it all to lowercase in 1.13.

**Comment by 4rz0** [comment]
That's why the suggestion, since it would fit into a mod that improves the keybind menu.
