### ISSUE TITLE
Update acceptedMinecraftVersions in the @Mod annotation

### ISSUE THREAD

**Issue by TheRandomLabs** [jaredlll08/Controlling#6]
The acceptedMinecraftVersions value in the @Mod annotation should be updated to include 1.11.2. I've tested it and it seems to work fine.

**Comment by jaredlll08** [comment]
100% tested? Since that would save me time setting up the workspace

**Comment by TheRandomLabs** [comment]
I went into Controls and tried the search function (worked fine) and the conflicts (also worked fine - the only conflicts were "NONE"). Not sure if this was intended, but when I pressed Ctrl, I couldn't press Ctrl again to get rid of it, and I had to use the button at the bottom right.
