### ISSUE TITLE
Crash when going to Controls

### ISSUE THREAD

**Issue by XTXMinightXTX** [jaredlll08/Controlling#70]
Narrowed the crash down to this mod from a bunch of others I had. 
From the Main Menu, if I go to Options, and then click Controls, the game crashes.
Crash Log:
[crash-2020-10-14_05.12.41-client.txt](https://github.com/jaredlll08/Controlling/files/5375618/crash-2020-10-14_05.12.41-client.txt)

Cheers

**Comment by jaredlll08** [comment]
Try without optifine please

**Comment by XTXMinightXTX** [comment]
Oh, I uploaded wrong crash report. Here's a new one where just Forge and the Controllable mod are installed.
[crash-2020-10-14_08.26.49-client.txt](https://github.com/jaredlll08/Controlling/files/5376375/crash-2020-10-14_08.26.49-client.txt)

Same thing happened when trying to get to the controls from in-game.
[crash-2020-10-14_08.30.26-client.txt](https://github.com/jaredlll08/Controlling/files/5376386/crash-2020-10-14_08.30.26-client.txt)

**Comment by jaredlll08** [comment]
`Controlling-7.0.0.8-deobf.jar`
You're using the deobfucated controlling file, which is meant for development environments.

Use this one instead:
https://www.curseforge.com/minecraft/mc-mods/controlling/download/3071408

I can't reproduce on the normal jar, so it should be fine.
