### ISSUE TITLE
Breaks Mouse Sensitivity Tweak mod by Sk1er

### ISSUE THREAD

**Issue by yanlin41020** [jaredlll08/Controlling#72]
Maybe because this mod overwrites the entire control system? I have different sensitivities for Y and X sensitivity using that mod, and the option disappears.

**Comment by jaredlll08** [comment]
At this point I don't even know if I can setup a 1.8.9 workspace, and with the way that Mouse Sensitivity Tweaks does things, I don't think I could realistically add support for it, they would need to add support for Controlling themselves.
