### ISSUE TITLE
Failed to load a valid ResourcePackInfo

### ISSUE THREAD

**Issue by TheButterbrotMan** [jaredlll08/Controlling#73]
Hello, i have a issue with this mod. At the start i tell me Controlling-7.0.0.10.jar failed to load ResourcePackInfo. 

I use the mod in my selfmade modpack.

LatestLog: https://pastebin.com/K8FNgHiZ
DebugLog: https://we.tl/t-WHQvpArUZT

Regards

**Comment by jaredlll08** [comment]
Thanks!
