### ISSUE TITLE
CMD + Left Win (MacOS)

### ISSUE THREAD

**Issue by Toadby** [jaredlll08/Controlling#79]
Forge 36.0.58, Controlling 7.0.0.14
When trying to register a keybind with Command as a modifier, it registers as "CMD + Left Win" and no other key can be added. I checked with Karabiner eventviewer to make sure this wasn't an issue with my keyboard (attached image). Any idea what might be going on? Any way around it? :)
<img width="517" alt="Screen Shot 2021-03-14 at 6 48 32 PM" src="https://user-images.githubusercontent.com/16440384/111093605-9dd90980-84f6-11eb-9d31-7cebeade31d4.png">

**Comment by jaredlll08** [comment]
Can you do this without controlling?
Like just with forge

**Comment by Toadby** [comment]
Oh my bad ! I assumed that multi keybindings wasn't in Forge by default :) I will have to contact them I suppose. Sorry about that!

**Comment by jaredlll08** [comment]
Added by Forge itself, I just change how the screen looks.

Going to close this then, if it ends up being on my side just let me know and I'll see if I can figure it out
