### ISSUE TITLE
Incompatibility with Beloved Keybindings Mod

### ISSUE THREAD

**Issue by Charismara** [jaredlll08/Controlling#80]
Hi,

i've created a mod which adds 2 buttons to all keybindinglist entries by replaceing the keybindinglist with my own.

Since replacing the keybindinglist will break your mod is there a way to add those buttons to your keybindinglist entries without adding your mod as hard dependency to my mod?

Those buttons whould require the keybinding object of the entry (to gather all information about the binding) and the render method to set the position and render the buttons.

**Comment by jaredlll08** [comment]
I don't see why you would need to replace the whole gui / list to add 2 buttons to each entry, you should be able to achieve the same result using ASM / mixins.

As for support, I can't give you an answer since I don't know what you're actually doing since your mod is closed source, so I don't really have any reference code to look at.

**Comment by Charismara** [comment]
To be honest, i've never used asm before and if i would use mixins i would need to add your mod as a hard dependency don't i?

The only thing i need to do is adding 2 Buttons to the displayed KeyBindingList.Entry and set their position in the KeyBindingList.Entry.render Method. 

Both buttons require a keybinding object to load the stored input key and the name of the keybinding.
`Widget button1 = new MyButton(keyBinding);`
`Widget button2 = new MyOtherButton(keyBinding);`

If you need some code i could send you my KeyBindingList + Entry classes.

**Comment by jaredlll08** [comment]
I was talking about mixin into the vanilla screen instead of replacing it.

Anyway, are you available on discord anywhere?

**Comment by Charismara** [comment]
Sure, you could add me on Discord if you want to: Professor#0815

**Comment by Charismara** [comment]
Fixed in referenced commit 👍
