### ISSUE TITLE
Can't hold down backspace to delete.

### ISSUE THREAD

**Issue by Foozey** [jaredlll08/Controlling#81]
As the title says, unlike the chat and other features of Minecraft, you can't hold down backspace when deleting characters in the search field. You have to tap backspace for every single character.

**Comment by jaredlll08** [comment]
I'm unable to reproduce.

As you can see below, holding backspace works perfectly fine, so you may have another mod that is messing with it.


https://user-images.githubusercontent.com/5553605/117561106-13df9400-b094-11eb-91b4-8cb395307077.mp4
