### ISSUE TITLE
Misclicked the Pateron button, got trapped in a loop where I couldn't leave the CONTROL screen without being forced back the the pateron menu screen

### ISSUE THREAD

**Issue by WilliamBlaze** [jaredlll08/Controlling#86]
the title say it all really. I was forced to end task my Minecraft just to get the bug to stop looping me to the pateron screen  repeatedly. I don't know if this is a hiccup on CONTOLLING's "pateron button" or some sort of mod conflict between Controlling and Forge itself or something else entirely. (Btw I'm using the latest 1.16.5 version of "Controlling" if that information helps any.)

Also I've ran into another rather annoying bug; it appears as if all Key conflicts that would normally appear in "red text" or in "orange text" are not appearing at all on the control screen when trying to assign keys, this "invisible keys" bug MIGHT be caused by a direct conflict between the Controlling mod and the mod "Just Enough Keys" - which adds a difference between left and right side of the keyboard when Registering the use of key triggers usable in Minecraft.

Meaning Left Alt, Left Shift, Left Ctrl keys register as one set of Key "suffix triggers" - while Right Alt, Right Shift, and Right Control keys register as  3 separately different keys for using as solo key triggers or as Key "Suffix Triggers" -because apparently Minecraft by default doesn't do as such and treats Shift as Shift, Alt as Alt, and Ctrl as Ctrl regardless of which side of the keyboard the Keystroke is happening from.
Again, I'm not sure How, but the conflict is being caused by Controlling and JEK being in the same mod folder actively at the same time. - as i've tested my mod load out without JEK and Controlling works fine without "Invisible keys" occurring, and then i've tested the same mod load out without Controlling installed, but with JEK installed - and there was no "invisible Keys" bug occurring.

The bug seemingly only happens when both mods are active at the same time... which seems strange considering all JEK is doing is basically adding 3 new triggers to the keyboard key combination trigger list in Minecraft - so in theory JEK shouldn't be causing Controlling to have such visual bugs, and like wise Controlling adds a means to quick search your key combinations and the ability to check what keys are free to assign quickly to fix such key binding conflicts. 

..But in applied practice the results aren't matching what's to be expected and I haven't the slightest clue why.

**Comment by jaredlll08** [comment]
As stated on the JEK github repo.
https://github.com/muqsit-0010/just-enough-keys#compatibility
> Incompatible with Controlling (JEK has its own search.)

I believe having that mod is also the reason that you got stuck in a loop since I can't reproduce this.

They really should mark Controlling as incompatible on CurseForge.
