### ISSUE TITLE
Not Showing

### ISSUE THREAD

**Issue by Ratugroote** [jaredlll08/Controlling#87]
When I have the mod on, it doesn't appear. I don't have much context sorry
![image_2021-08-02_105100](https://user-images.githubusercontent.com/81857861/127792416-0099ed67-f36c-42a2-a639-acdef56124ae.png)

**Comment by jaredlll08** [comment]
There has to be context.
What mc version?
What controlling version?
What forge version?
What other mods?

**Comment by jaredlll08** [comment]
Closing due to no information.
