### ISSUE TITLE
1.8.9 no french language ?

### ISSUE THREAD

**Issue by enzomtpYT** [jaredlll08/Controlling#90]
Hi ! I wanna know why is controlling doing me that : 
![image](https://user-images.githubusercontent.com/40535918/132133842-d435fab2-de5d-4f67-9a74-49dfb5e9af4a.png)
is this because there is any language ? Can i create it myself ?

**Comment by jaredlll08** [comment]
I have no idea why it is doing that, the French lang file is there, so I have no idea why it isn't using it.

1.8.9 is also no longer supported.
