### ISSUE TITLE
Major issue

### ISSUE THREAD

**Issue by SeanDaBitch** [jaredlll08/Controlling#98]
![IMG_5111](https://user-images.githubusercontent.com/93109251/141603751-f01ce336-6575-4826-8b97-7e261377de16.jpg)
Whatever the fuck this is

**Comment by jaredlll08** [comment]
Mc version?

controlling version?

What language is your game set to?

**Comment by SeanDaBitch** [comment]
English (US)
1.8.9 forge (no mods installed) 
Latest 1.8.9 controlling version

**Comment by jaredlll08** [comment]
Duplicate of #90.

I can't even setup a 1.12 workspace let alone a 18.9 workspace.
