### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by SeanDaBitch** [jaredlll08/Controlling#99]
Will this bug be fixed: https://i.imgur.com/UbdxSwA.png

**Comment by SeanDaBitch** [comment]
I'm running forge 1.8.9
I am using Controlling-7.0.0.2
I tried the mod both with and without other mods and it still has this glitch

**Comment by jaredlll08** [comment]
Duplicate of https://github.com/jaredlll08/Controlling/issues/98

NO.

As I said in that issue, I can't setup a 1.8.9 workspace even if I wanted to.

Forge made changes to their maven that broke older versions.
